name: ci

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps: #code checkout. and prepare environment (node install)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      # - run: npx nx run-many -t docker-build -p client server    //run many
      - run: git branch -a
      - run: npx nx affected -t docker-build --base=origin/main~1 --head=HEAD #//run affected

      - name: Login to Docker Hub and Push Images (if present)
        run: |

          if [ "$(docker inspect --type=image slokesh/client-nx 2> /dev/null --format='present')" == "present" ] ||  [ "$(docker inspect --type=image slokesh/server-nx 2> /dev/null --format='present')" == "present" ]
          then
             docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
             if [[ "$(docker inspect --type=image slokesh/client-nx 2> /dev/null --format='present')" == "present" ]]
             then
              echo "Uploading slokesh/client-nx"
              docker push slokesh/client-nx
             fi

             if [[ "$(docker inspect --type=image slokesh/server-nx 2> /dev/null --format='present')" == "present" ]]; then
              echo "Uploading slokesh/slokesh/server-nx"
              docker push slokesh/server-nx
             fi

          else   
            echo "No images to upload"
          fi
